### ISSUE TITLE
error..!

### ISSUE THREAD

**Issue by jpadron1983** [Kucoin-academy/high-frequency#12]
r# ./high_frequency.py
Traceback (most recent call last):
  File "./high_frequency.py", line 40, in <module>
    price_bf = hf.get_symbol_price(hf.symbol_b)
  File "./high_frequency.py", line 32, in get_symbol_price
    return float(ticker['price'])
KeyError: 'price'

**Comment by 1bazinga25** [comment]
Hi, I test it and it works fine, and how does your config.json look like?

**Comment by IMRC21** [comment]
Having the same issue as you
